src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $insurance_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vehicle", mappedBy="owner")
     */
    private $vehicles;

    public function __construct()
    {
        $this->vehicles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(?string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getInsuranceName(): ?string
    {
        return $this->insurance_name;
    }

    public function setInsuranceName(?string $insurance_name): self
    {
        $this->insurance_name = $insurance_name;

        return $this;
    }

    /**
     * @return Collection|Vehicle[]
     */
    public function getVehicles(): Collection
    {
        return $this->vehicles;
    }

    public function addVehicle(Vehicle $vehicle): self
    {
        if (!$this->vehicles->contains($vehicle)) {
            $this->vehicles[] = $vehicle;
            $vehicle->setOwner($this);
        }

        return $this;
    }

    public function removeVehicle(Vehicle $vehicle): self
    {
        if ($this->vehicles->contains($vehicle)) {
            $this->vehicles->removeElement($vehicle);
            // set the owning side to null (unless already changed)
            if ($vehicle->getOwner() === $this) {
                $vehicle->setOwner(null);
            }
        }

        return $this;
    }
}

src/Entity/Vehicle.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VehicleRepository")
 */
class Vehicle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $year_produced;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $engine_type;

    /**
     * @ORM\Column(type="smallint")
     */
    private $engine_displacement;

    /**
     * @ORM\Column(type="smallint")
     */
    private $engine_power;

    /**
     * @ORM\Column(type="smallint")
     */
    private $max_speed;

    /**
     * @ORM\Column(type="smallint")
     */
    private $max_seats;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="vehicles")
     */
    private $owner;

    /**
     * @ORM\Column(type="json")
     */
    private $pictures = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getYearProduced(): ?string
    {
        return $this->year_produced;
    }

    public function setYearProduced(string $year_produced): self
    {
        $this->year_produced = $year_produced;

        return $this;
    }

    public function getEngineType(): ?string
    {
        return $this->engine_type;
    }

    public function setEngineType(string $engine_type): self
    {
        $this->engine_type = $engine_type;

        return $this;
    }

    public function getEngineDisplacement(): ?int
    {
        return $this->engine_displacement;
    }

    public function setEngineDisplacement(int $engine_displacement): self
    {
        $this->engine_displacement = $engine_displacement;

        return $this;
    }

    public function getEnginePower(): ?int
    {
        return $this->engine_power;
    }

    public function setEnginePower(int $engine_power): self
    {
        $this->engine_power = $engine_power;

        return $this;
    }

    public function getMaxSpeed(): ?int
    {
        return $this->max_speed;
    }

    public function setMaxSpeed(int $max_speed): self
    {
        $this->max_speed = $max_speed;

        return $this;
    }

    public function getMaxSeats(): ?int
    {
        return $this->max_seats;
    }

    public function setMaxSeats(int $max_seats): self
    {
        $this->max_seats = $max_seats;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getPictures(): ?array
    {
        return $this->pictures;
    }

    public function setPictures(array $pictures): self
    {
        $this->pictures = $pictures;

        return $this;
    }
}

templates/main/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}La liste des personnalitées !{% endblock %}

{% block body %}

<div class="row">

    {# <h1 class="col-8 offset-1 mt-5 text-center">La liste des personnalitées ! {{ users.getTotalItemCount }}</h1> #}

    <div class="col-sm-10 offset-sm-1 my-4 bg-info text-light shadow border border-light">

        <p class="text-center my-3 bg-dark">
            <span class="mx-2">'Trier par Id', 'u.id'</span>
            <span class="mx-2">'Trier par Email', 'u.email'</span>
            <span class="mx-2">'Trier par Rôles', 'u.roles'</span>
            {# <span class="mx-2">{{ knp_pagination_sortable(users, 'Trier par Id', 'u.id') }}</span> #}
            {# <span class="mx-2">{{ knp_pagination_sortable(users, 'Trier par Email', 'u.email') }}</span> #}
            {# <span class="mx-2">{{ knp_pagination_sortable(users, 'Trier par Rôles', 'u.roles') }}</span> #}
        </p>

        {# <div class="my-3 text-center"><div class="d-inline-block">{{ knp_pagination_render(users) }}</div> #}
    </div>

    <table class="table bg-light text-dark">
        <thead>
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th>Rôles</th>
            </tr>
        </thead>
        <tbody>
        {# {% for user in users %} #}
        <tr>
            <td>alo</td>
            <td>ki</td>
            <td>koi</td>
            {# <td>{{ user.id }}</td> #}
            {# <td>{{ user.email }}</td> #}
            {# <td>{{ user.roles|join(' :: ') }}</td> #}
        </tr>
        {# {% endfor %} #}
        </tbody>
    </table>

    {# <div class="my-3 text-center"><div class="d-inline-block">{{ knp_pagination_render(users) }}</div> #}

    {# bouclette à l'ancienne sans join
    {% for user in users %}
        {% for alo in user.roles %}
            {{ alo }}
        {% endfor %}
    {% endfor %} #}

</div>

{% endblock %}

templates/main/carDetail.html.twig
{% extends 'base.html.twig' %}
{% form_theme formDetailsVehicle "form_style.html.twig" %}

{% block title %}Fiche technique{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
    <div class="alert alert-success col-12">{{ message }}</div>
{% endfor %}
{% for message in app.flashes('error') %}
    <div class="alert alert-danger col-12">{{ message }}</div>
{% endfor %}

{# Intégration des photos miniatures et de la fiche signalétique #}
<h2 class="text-center my-3">Fiche technique</h2>

<div class="d-flex flex-wrap justify-content-center justify-content-md-between">
    {# Affichage des photos minatures disponibles (entre 1 et 5 photos) sur une ligne #}
    {% for picture in vehicle.pictures %}
        {# <p class="thumbnail"> #}
        <div data-img="{{ asset('images/pictures/' ~ picture) }}" class="mw-100 my-1 img-thumbnail btn viewer-event"
            style="background-image: url('{{ asset('images/pictures/' ~ picture) }}');
            height:150px; width:275px; background-size: cover; background-position: center center;"
        ></div>
        {# </p> #}
    {% endfor %}
</div>

{# flex justify-content-center in phone screen, but next, in small screen it is justify-content-around #}
<div class="d-flex flex-wrap justify-content-center justify-content-sm-around">

    {# Bloc caractéristiques techniques #}
    {# phone screen col-10, height:100% && minimum-width:100% #}
    <div class="col-10 col-sm-3 border border-warning my-2 p-3 h-100 mw-100">
        <h3 class="text-uppercase font-weight-bold">Caractéristiques techniques</h3>
        <ul class="list-unstyled text-truncate">
            <li>Marque : {{ vehicle.brand }}</li>
            <li>Modèle : {{ vehicle.model }}</li>
            <li>Année : {{ vehicle.yearProduced }}</li>
            <li>Architecture moteur : {{ vehicle.engineType }}</li>
            <li>Cylindrée : {{ vehicle.engineDisplacement }} cm3</li>
            <li>Puissance : {{ vehicle.enginePower }} ch</li>
            <li>Vitesse maxi : {{ vehicle.maxSpeed }} km/h</li>
            <li>Nombre de places : {{ vehicle.maxSeats }} places</li>
        </ul>
    </div>

    {# Bloc coordonnées propriétaire #}
    <div class="col-10 col-md-3 border border-warning my-2 p-3 h-100 mw-100">
        <h3 class="text-uppercase font-weight-bold">Coordonnées du propriétaire</h3>
        <ul class="list-unstyled text-truncate">
            <li>Nom : {{ vehicle.owner.lastname }}</li>
            <li>Prénom : {{ vehicle.owner.firstname }}</li>
            <li>Localisation : {{ vehicle.owner.postcode }} {{ vehicle.owner.city }}</li>
            <li>Téléphone : {{ vehicle.owner.phoneNumber }}</li>
            <li>Email : {{ vehicle.owner.email }}</li>
            <li>Assurance : {{ vehicle.owner.insuranceName }}</li>
        </ul>
    </div>

    {% if (verificationUserOwnage) %}
    <div class="col-10 col-sm-3">
        <h2 class="text-center my-3">Modifier véhicule</h2>
        {{ form(formDetailsVehicle) }}
    </div>
    {% endif %}

</div>

{% endblock %}

{% block javascripts %}
    {# Affichage photo en grand format en overlay #}
    <script src="{{ asset('js/viewer.js') }}"></script>
    {# Correction d'un bug de bootstrap qui n'écrit pas le nom du fichier téléversé #}
    <script src="{{ asset('js/fix-bootstrap-input-file.js') }}"></script>
{% endblock %}

templates/main/carList.html.twig
{% extends 'base.html.twig' %}

{% block title %}La collection{% endblock %}

{% block stylesheets %}
{# ne récupère pas automatiquement le dossier d'images de leaflet, donc : CDN #}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css">
{# need /img #}
{# <link rel="stylesheet" href="{{ asset('css/leaflet.css') }}"> #}
<link rel="stylesheet" href="{{ asset('css/MarkerCluster.css') }}">
<link rel="stylesheet" href="{{ asset('css/MarkerCluster.Default.css') }}">
{% endblock %}

{% block body %}
<div class="row">

    {#Intégration de la collection#}
    <div class="col-md-6">
        <h2 class="text-center my-3">La Collection</h2>

        <div class="d-flex flex-wrap justify-content-center justify-content-sm-around">
            {% if vehicles is not empty %}
                {% for vehicle in vehicles %}
                    <a href="{{ path('car_detail', { id: vehicle.id }) }}" class="mw-100 text-decoration-none text-dark">
                        {# <div class="mw-100 img-thumbnail" style="background-image: url('{{ asset('images/pictures/' ~ vehicle.pictures[0]) }}');height:250px; width:450px; background-size: cover; background-position: center center;"> #}
                        <div class="mw-100 img-thumbnail"
                            {% if vehicle.pictures[0] is defined %}
                                style="background-image:url('{{ asset('images/pictures/' ~ vehicle.pictures[0]) }}');
                                height:250px; width:450px; background-size:cover; background-position:center center;"
                            {% endif %}
                        ></div>
                        <p class="">{{ vehicle.brand }} {{ vehicle.model }}</p>
                    </a>
                    {# <a href="{{ path('car_detail', { id: vehicle.id }) }}" class="list-group-item list-group-item-action">{{ vehicle.pictures }}</a> #}
                {% endfor %}
            {% else %}
                <p class="alert alert-danger">Aucune voiture disponible dans la collection.</p>
            {% endif %}
        </div>

    </div>

    <div class="col-md-6">
        <h2 class="text-center my-3">La Localisation</h2>

        <div class="text-center">
            <p id="champ-food">remplir les champs dans l'ordre svp</p>
            <p>
                <label for="champ-city">Ville : </label>
                <input type="text" id="champ-city" placeholder="Autun" value="">
            </p>
            <p>
                <label for="champ-distance">distance : </label>
                <input type="range" min="1" max="1000" id="champ-distance" placeholder="400" value="">
            </p>
            <p id="value-distance"></p>
        </div>

        <div class="col-md-10 offset-md-1 vh-100 my-4 mx-auto" id="map"></div>

    </div>

</div>

{% endblock %}

{% block javascripts %}
<script src="{{ asset('js/leaflet.js') }}"></script>
{# leaflet extension : regroup the markers #}
<script src="{{ asset('js/leaflet.markercluster.js') }}"></script>
<script src="{{ asset('js/api.openstreetmaps.js') }}"></script>
{% endblock %}

templates/main/conditions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Condition Générales d'utilisation{% endblock %}
{% block stylesheets %}{% endblock %}

{% block body %}
<div class="row">
    <div class="col-10 offset-1 py-2 text-black rounded text-center text-sm-left">
        <h2 class="my-3">Conditions générales d’utilisation du site LocAutoVintage</h2>
        <hr>
        <p>
            Article 1 : Objet
            Les présentes CGU ou Conditions Générales d’Utilisation encadrent juridiquement l’utilisation des services du site LoAutoVintage (ci-après dénommé « le site »).
            Constituant le contrat entre la société La Petite Perle, l’Utilisateur, l’accès au site doit être précédé de l’acceptation de ces CGU. L’accès à cette plateforme signifie l’acceptation des présentes CGU.
        </p>
        <p>
            Article 2 : Mentions légales
            L’édition du site lapetiteperle est assurée par la société La Petite Perle inscrite au RCS sous le numéro 451 432 228, dont le siège social est localisé au 3 Rue Docteur Joubert, 59110, La Madeleine, France Métropolitaine.
            L’hébergeur du site LoAutoVintage.fr est la société BlaBla, sise au 5 Rue des Sapins, 75000 Paris, France.
        </p>
        <p>
            Article 3 : Accès au site
            Le site lapetiteperle permet d’accéder gratuitement aux services suivants :
                • Vente de bijoux (en or, en argent…) ;
                • Location de bijoux (en or, en argent…) ;
                • Dépôt-vente de bijoux.
            Le site est accessible gratuitement depuis n’importe où par tout utilisateur disposant d’un accès à Internet. Tous les frais nécessaires pour l’accès aux services (matériel informatique, connexion Internet…) sont à la charge de l’utilisateur.
            L’accès aux services dédiés aux membres s’effectue à l’aide d’un identifiant et d’un mot de passe.
            Pour des raisons de maintenance ou autres, l’accès au site peut être interrompu ou suspendu par l’éditeur sans préavis ni justification.
        </p>
        <p>
            Article 4 : Collecte des données
            Pour la création du compte de l’Utilisateur, la collecte des informations au moment de l’inscription sur le site est nécessaire et obligatoire. Conformément à la loi n°78-17 du 6 janvier relative à l’informatique, aux fichiers et aux libertés, la collecte et le traitement d’informations personnelles s’effectuent dans le respect de la vie privée.
            Suivant la loi Informatique et Libertés en date du 6 janvier 1978, articles 39 et 40, l’Utilisateur dispose du droit d’accéder, de rectifier, de supprimer et d’opposer ses données personnelles. L’exercice de ce droit s’effectue par :
                • Le formulaire de contact ;
                • Son espace client.
        </p>
        <p>
            Article 5 : Propriété intellectuelle
            Les marques, logos ainsi que les contenus du site lapetiteperle (illustrations graphiques, textes…) sont protégés par le Code de la propriété intellectuelle et par le droit d’auteur.
            La reproduction et la copie des contenus par l’Utilisateur requièrent une autorisation préalable du site. Dans ce cas, toute utilisation à des usages commerciaux ou à des fins publicitaires est proscrite.
        </p>
        <p>
            Article 6 : Responsabilité
            Bien que les informations publiées sur le site soient réputées fiables, le site se réserve la faculté d’une non-garantie de la fiabilité des sources.
            Les informations diffusées sur le site lapetiteperle sont présentées à titre purement informatif et sont sans valeur contractuelle. En dépit des mises à jour régulières, la responsabilité du site ne peut être engagée en cas de modification des dispositions administratives et juridiques apparaissant après la publication. Il en est de même pour l’utilisation et l’interprétation des informations communiquées sur la plateforme.
            Le site décline toute responsabilité concernant les éventuels virus pouvant infecter le matériel informatique de l’Utilisateur après l’utilisation ou l’accès à ce site.
            Le site ne peut être tenu pour responsable en cas de force majeure ou du fait imprévisible et insurmontable d’un tiers.
            La garantie totale de la sécurité et la confidentialité des données n’est pas assurée par le site. Cependant, le site s’engage à mettre en œuvre toutes les méthodes requises pour le faire au mieux.
        </p>
        <p>
            Article 7 : Liens hypertextes
            Le site peut être constitué de liens hypertextes. En cliquant sur ces derniers, l’Utilisateur sortira de la plateforme. Cette dernière n’a pas de contrôle et ne peut pas être tenue responsable du contenu des pages web relatives à ces liens.
        </p>
        <p>
            Article 8 : Cookies
            Lors des visites sur le site, l’installation automatique d’un cookie sur le logiciel de navigation de l’Utilisateur peut survenir.
            Les cookies correspondent à de petits fichiers déposés temporairement sur le disque dur de l’ordinateur de l’Utilisateur. Ces cookies sont nécessaires pour assurer l’accessibilité et la navigation sur le site. Ces fichiers ne comportent pas d’informations personnelles et ne peuvent pas être utilisés pour l’identification d’une personne.
            L’information présente dans les cookies est utilisée pour améliorer les performances de navigation sur le site locautovintage.
            En naviguant sur le site, l’Utilisateur accepte les cookies. Leur désactivation peut s’effectuer via les paramètres du logiciel de navigation.
        </p>
        <p>
            Article 9 : Publication par l’Utilisateur
            Le site lapetiteperle permet aux membres de publier des commentaires.
            Dans ses publications, le membre est tenu de respecter les règles de la Netiquette ainsi que les règles de droit en vigueur.
            Le site dispose du droit d’exercer une modération à priori sur les publications et peut refuser leur mise en ligne sans avoir à fournir de justification.
            Le membre garde l’intégralité de ses droits de propriété intellectuelle. Toutefois, toute publication sur le site implique la délégation du droit non exclusif et gratuit à la société éditrice de représenter, reproduire, modifier, adapter, distribuer et diffuser la publication n’importe où et sur n’importe quel support pour la durée de la propriété intellectuelle. Cela peut se faire directement ou par l’intermédiaire d’un tiers autorisé. Cela concerne notamment le droit d’utilisation de la publication sur le web et sur les réseaux de téléphonie mobile.
            À chaque utilisation, l’éditeur s’engage à mentionner le nom du membre à proximité de la publication.
            L’Utilisateur est tenu responsable de tout contenu qu’il met en ligne. L’Utilisateur s’engage à ne pas publier de contenus susceptibles de porter atteinte aux intérêts de tierces personnes. Toutes procédures engagées en justice par un tiers lésé à l’encontre du site devront être prises en charge par l’Utilisateur.
            La suppression ou la modification par le site du contenu de l’Utilisateur peut s’effectuer à tout moment, pour n’importe quelle raison et sans préavis.
        </p>
        <p>
            Article 10 : Durée du contrat
            Le présent contrat est valable pour une durée indéterminée. Le début de l’utilisation des services du site marque l’application du contrat à l’égard de l’Utilisateur.
        </p>
        <p>
            Article 11 : Droit applicable et juridiction compétente
            Le présent contrat est soumis à la législation française. L’absence de résolution à l’amiable des cas de litige entre les parties implique le recours aux tribunaux français compétents pour régler le contentieux.
        </p>
    </div>
</div>

{% endblock %}

{% block javascript %}{% endblock %}

templates/main/contact.html.twig
{% extends "base.html.twig" %}
{% form_theme form "form_style.html.twig" %}

{% block title %}Contact{% endblock %}
{% block stylesheets %}
    {# Insertion du fichier JS dans le block stylesheets, ce n'est pas une erreur, la documentation de Recaptcha préconise en effet d'intégrer ce fichier JS dans le head #}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
    <div class="alert alert-success col-12">{{ message }}</div>
{% endfor %}
<div class="row">

        {# display none if screen maximum small. 6 columns in case of screen small
        background-image in the css : .img_home ; vh-100 for resizing #}
        <div class="d-none d-sm-block col-sm-6 img_home vh-100"></div>

    <div class="col-sm-6">
        <h2 class="text-center my-3">Contactez-nous</h2>

        <div class="row col-sm-8 offset-sm-2 d-inline-flex justify-content-center">
            {{ form_start(form) }}

            {{ form_errors(form) }}

            {{ form_row(form.from) }}
            {{ form_row(form.subject) }}
            {{ form_row(form.body) }}

            {# Affichage du captcha avec la clé publique récupérée directement grâce à la passerelle faite dans twig.yaml #}
            <div class="form-group">
                <div class="g-recaptcha" data-sitekey="{{ google_recaptcha_site_key }}"></div>
            </div>
            {{ form_row(form.save) }}

            {{ form_end( form )}}
        </div>

    </div>

</div>

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}index /{% endblock %}
{% block stylesheets %}{% endblock %}

{% block body %}

    {% for message in app.flashes('success') %}
    <div class="alert alert-success col-12">{{ message }}</div>
    {% endfor %}

    {#Intégration de l'image l'image#}
    <div class="row img_home">
        <div class="col-10 col-sm-8 col-md-4 offset-0 offset-sm-1 offset-md-1 m-5 py-2 text-light shadow rounded h-75 overflow-auto overlay-black">
            <h3>Lorem ipsum dolor sit amet</h3>
            <p>
                consectetur adipisicing elit. Inventore, maxime. Quibusdam nobis, distinctio harum aperiam tempora inventore, temporibus provident nisi totam laboriosam ab omnis itaque illo voluptatibus.
                Non, perspiciatis velit. Fuga ipsum quisquam non corrupti ex odio sapiente pariatur velit! Modi, expedita.
            </p>
            <p>
                Sit delectus repudiandae, impedit autem rem dolor dignissimos maiores qui doloremque sequi suscipit tempora exercitationem necessitatibus pariatur totam.
                Neque at quisquam est deserunt assumenda suscipit maxime esse corporis tempore delectus voluptatibus expedita ab sed dicta a, quibusdam accusantium ratione veritatis dolorum harum?
            </p>
            <p>
                Consectetur neque porro saepe veniam recusandae praesentium? Excepturi, consequatur quam dignissimos magni aperiam, optio esse animi perspiciatis expedita eos cum quos officia non
                laboriosam blanditiis delectus quod enim, quis cupiditate!Quibusdam accusantium ratione veritatis dolorum harum est.
            </p>
        </div>
    </div>
    <div class="row mb-5">
        <p class="col-6 offset-3 mb-0 py-5 border-bottom border-dark text-center">
            Notre collection de voitures classiques comprend des modèles emblématiques mises à votre disposition par des propriétaires passionnés. Grâce à notre sélection, vous trouverez votre voiture partenaire idéale.
            Faites-vous plaisir en découvrant les petites routes de France au volant d’une voiture rare et ancienne.
        </p>
    </div>

{% endblock %}

{% block javascript %}{% endblock %}

templates/main/vehicle.html.twig
{% extends 'base.html.twig' %}
{% form_theme formVehicle "form_style.html.twig" %}

{% block title %}Ajoutez votre véhicule{% endblock %}

{% block body %}

{# T: si tu veux bien ajouter une belle image de w210 e300td en fond de page #}

<div class="row">

  <div class="col-sm-6 offset-sm-3">
    <h2 class="text-center my-3">Ajout d'un nouveau véhicule</h2>
    {{ form(formVehicle) }}
  </div>

</div>

{% endblock %}

{% block javascripts %}
    {# Correction d'un bug de bootstrap qui n'écrit pas le nom du fichier téléversé #}
    <script src="{{ asset('js/fix-bootstrap-input-file.js') }}"></script>
{% endblock %}